---
title: "R Notebook"
output: html_notebook
---



```{r}
library("ggplot2")
library("dplyr")
library("reshape")
data <- read.table("data/USA_5x5.txt",header = TRUE, sep = "", skip = 1)

data <- data[data$Total != ".",]
data <- data[table(data$Year)[data$Year] > 8, ]

data$Age <-as.numeric( 
    regmatches( as.character(data$Age) ,regexpr("([0-9]*$)", as.character(data$Age) ))
)

data$Age[data$Age == 0] <- 1
data$Age[is.na(data$Age)] <- 110
data$Female <-as.numeric(as.character(data$Female))
data$Male <-as.numeric(as.character(data$Male))
data$Total <-as.numeric(as.character(data$Total))

head(data, 20)
```

```{r}
year <- "1930-1934" 
#"1930-1934"
subdata <- data[data$Year == year ,c("Age", "Female", "Male", "Total")]

head(subdata)
```

```{r}
meltsubdata <- melt(subdata, id.vars = c( "Age"))
colnames(meltsubdata)[3] <- "Mortality"
```

```{r}
  p <- ggplot(data = meltsubdata, aes(x = Age, y = Mortality) )
  p <- p + geom_line( size=2, alpha = 0.6, aes(color = variable)) 
  #p <- p +  scale_x_discrete(name = "Age",breaks=subdata$Ageto,
     #   labels=subdata$Age)
  p
```

```{r}
curve <-subdata
curve[1, 2:4] <- 1
for (t in 2:length(curve$Age)){
   curve[t, 2:4] <- curve[t-1, 2:4] *(1 - subdata[t-1, 2:4] )
}
head(curve)
```
```{r}
meltcurve <- melt(curve, id.vars = c( "Age"))
colnames(meltcurve)[3] <- "Survival"
  p2 <- ggplot(data = meltcurve, aes(x = Age, y = Survival) )
  p2 <- p2 + geom_line( size=1, alpha = 0.6, aes(color = variable)) 
  p2
```

## Differences between years
```{r}
index <-c("1930-1934", "1940-1944", "1950-1954", "1960-1964", "1970-1974")
 yeardata <- data[data$Year %in% index,]
  p3 <- ggplot(data = yeardata, aes(x = Age, y = Total) )
  p3 <- p3 + geom_line( size=1, alpha = 0.6, aes(color = Year)) 
  p3
```

##

```{r}
yeardata <- data[data$Year %in% index,]
yearcurve <- NULL
for (y in index){
    subdata <- data[data$Year == y ,]
    curve <-subdata
    curve[1, 3:5] <- 1 # initialize
    for (t in 2:length(curve$Age)){
        curve[t, 3:5] <- curve[t-1, 3:5] *(1 - subdata[t-1, 3:5] )
    }
    yearcurve <- rbind(yearcurve, curve)
}

meltyear <- melt(yeardata, id.vars = c( "Year","Age"))
meltcurve <- melt(yearcurve, id.vars = c( "Year","Age"))
```


```{r}
years <- c("1930-1934", "1940-1944", "1950-1954")
groups <- c("Total")

subdata <- meltyear[meltyear$Year %in% years & meltyear$variable %in% groups, ]
colnames(subdata)[4] <- "Mortality"
subcurve <- meltcurve[meltcurve$Year %in% years & meltcurve$variable %in% groups, ]
colnames(subcurve)[4] <- "Survival"

```


```{r}
  p3 <- ggplot(data = subdata, aes(x = Age, y = Mortality) )
if (length(years)>1) {
  p3 <- p3 + geom_line( size=1, alpha = 0.6, aes(color = Year)) 
  p3 <- p3 + facet_grid(.~ variable)}else {
  p3 <- p3 + geom_line( size=1, alpha = 0.6, aes(color = variable))   
}
  p3
```

